# Generated by Django 3.0.5 on 2020-09-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='userfollowing',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
    ]
